<?php
/**
 * System script for updating database when upgrading from modera 4.00 to 4.01 (with nice urls
 * support).
 *
 * @version $Id: 4.00-to-4.01.php 306 2006-10-09 11:14:46Z priit.pyld $
 */

include('../class/config.php');
include(SITE_PATH . '/class/Database.php');
include(SITE_PATH . '/class/mysql.class.php');

?>
<html>
<head>
    <title>Upgrade modera.net database from 4.00 to 4.01</title>
</head>
<body>
<h1>Updating database:</h1>
<ul>
<?php

$sql = new Sql();
$sql->connect();
$db = new Database($sql);

// upgrade settings table
if (false === $db->fetch_first_value('SHOW COLUMNS FROM `settings` LIKE ?', 'niceurls')) {
    $db->query('ALTER TABLE `settings` ADD `niceurls` TINYINT NOT NULL DEFAULT 0 AFTER `translator`');
    if ($db->affected_rows()) {
        echo "<li>table `<em>settings</em>` updated</li>\n";
    } else {
        echo "<li style=\"color: red;\">could not update table `<em>settings</em>`</li>\n";
    }
} else {
    echo "<li>table `<em>settings</em>` already up to date</li>\n";
}

// upgrade structure table
if (false === $db->fetch_first_value('SHOW COLUMNS FROM `structure` LIKE ?', 'uri_alias')) {
    $db->query('ALTER TABLE `structure` ADD `uri_alias` VARCHAR(255) NOT NULL AFTER `perm_other`');
    if ($db->affected_rows()) {
        echo "<li>table `<em>structure</em>` updated</li>\n";
    } else {
        echo "<li style=\"color: red;\">could not update table `<em>structure</em>`</li>\n";
    }
} else {
    echo "<li>table `<em>structure</em>` already up to date</li>\n";
}

// upgrade content table
if (false === $db->fetch_first_value('SHOW COLUMNS FROM `content` LIKE ?', 'uri_alias')) {
    $db->query('ALTER TABLE `content` ADD `uri_alias` VARCHAR(255) NOT NULL AFTER `redirectto`');
    if ($db->affected_rows()) {
        echo "<li>table `<em>content</em>` updated</li>\n";
    } else {
        echo "<li style=\"color: red;\">could not update table `<em>content</em>`</li>\n";
    }
} else {
    echo "<li>table `<em>content</em>` already up to date</li>\n";
}

// update editor_all category in translations table
$db->query('DETELE FROM `tokens` WHERE `domain` = \'editor_all\'');
$db->query('DETELE FROM `translations` WHERE `domain` = \'editor_all\'');

$queries = "
INSERT INTO `tokens` VALUES ('editor_all', 'bookmark_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'cancel', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'top_border', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'custom_colors', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'border_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'color', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'box_Shading', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'box_Dimension', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'apply', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'no_border', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'outside_border', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'left_border', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'right_border', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'bottom_border', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'box_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'characters_1', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'characters_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'colors_1', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'colors_NamedColors', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'colors_216WebSafe', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'colors_New', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'colors_Current', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'colors_btnAddToCustom', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'colors_btnCancel', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'colors_btnRemove', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'colors_btnApply', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'colors_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Save', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_FullScreen', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_CheckSpelling', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_TextFormatting', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_ListFormatting', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_ParagraphFormatting', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_CustomCSS', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_StylesFormatting', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Paragraph', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_FontName', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_FontSize', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Strikethrough', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_JustifyLeft', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_JustifyCenter', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_JustifyRight', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_JustifyFull', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Numbering', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Bullets', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Indent', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Outdent', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_LeftToRight', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_RightToLeft', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_ForegroundColor', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_BackgroundColor', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Hyperlink', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_SpecialCharacters', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'image', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Flash', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Media', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_ContentBlock', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_InternalLink', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Object', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_InsertTable', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_TableSize', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_EditTable', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_EditCell', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Table', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_BorderShading', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_ShowHideGuidelines', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Absolute', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_PastefromWord', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Line', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_FormEditor', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Form', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_TextField', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_List', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Checkbox', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_RadioButton', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_HiddenField', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_FileField', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Clean', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_ViewEditSource', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_TagSelector', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_ClearAll', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Tags', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Heading_1', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Heading_2', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Heading_3', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Heading_4', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Heading_5', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Heading_6', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Preformatted', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_NormalP', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_NormalDIV', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Size_1', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Size_2', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Size_3', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Size_4', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Size_5', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Size_6', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Size_7', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_deleteallcontents', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_RemoveTag', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_BoxFormatting', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_AdvancedTableInsert', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_EditTableCell', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_Print', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_PasteText', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'flash_Quality', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'flash_Align', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'flash_Loop', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'flash_ClassID', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'flash_CodeBase', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'flash_PluginsPage', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'flash_Low', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'flash_High', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'flash_NotSet', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'more_colors', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'flash_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'button', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_button_Submit', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_button_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_check_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_file_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_form_Action', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_form_Method', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_form_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_hidden_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_list_Multipleselect', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_list_btnAdd', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_list_btnUp', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_list_btnDown', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_list_btnDel', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_list_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'default', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'checked', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_radio_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'type', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'name', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_text_MaxLength', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_text_NumLine', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'value', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_text_Text', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_text_Textarea', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_text_Password', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'unchecked', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'form_text_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'hyperlink_Page', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'bookmark', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'hyperlink_Target', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'hyperlink_Title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'hyperlink_Linktype', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'hyperlink_Plainlink', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'hyperlink_Imagelink', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'hyperlink_Self', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'hyperlink_Blank', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'hyperlink_Parent', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'image_Title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'image_Border', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'image_absBottom', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'image_absMiddle', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'image_textTop_2', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'reset', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'image_background_ImageSource', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'image_background_Repeat', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'image_background_HorizontalAlign', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'image_background_VerticalAlign', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'image_background_Norepeat', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'image_background_Repeathorizontally', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'image_background_Repeatvertically', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'background_image', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'list_Numbered', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'list_Bulleted', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'list_StartingNumber', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'list_UsingImageurl', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'left_margin', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'list_Pleaseselectalist', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'list_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'source', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'media_AutoStart', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'media_ShowControls', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'media_ShowStatusBar', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'media_ShowDisplay', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'media_AutoRewind', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'media_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'paragraph_Indentation', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'paragraph_WordSpacing', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'paragraph_LineHeight', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'paragraph_TextCase', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'paragraph_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'paste_word_txtLang', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'paste_word_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'percent_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'preview_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'search_Matchcase', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'search_Matchwholeword', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'search_btnSearch', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'replace', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'search_btnReplaceAll', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'close', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'search_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'source_html_txtLang', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'search', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'cut', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'copy', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'paste', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'undo', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'redo', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'source_html_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'spellcheck_ieSpell', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'spellcheck_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'styles', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'styles_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'class_name', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'youre_selecting_body_element', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'please_select_a_text', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'custom_css', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_edit_SpanSplitRow', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_edit_SpanSplitColumn', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_edit_Fixedtablewidth', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_edit_Fixedtableheight', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'autofit_to_window', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'alignment', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'margin', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_edit_CellSpacing', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_edit_CellPadding', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_edit_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'autofit', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'properties', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'width', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_editCell_6', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'height', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'autofit_to_contents', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_editCell_9', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_editCell_10', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'white_space', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'css_text', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_editCell_btnImage', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_editCell_btnText', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'border_style', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'pixels', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'percent', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_editCell_30', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_editCell_31', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'left', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'center', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'right', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'justify', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'no_wrap', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'pre', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_editCell_43', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_editCell_44', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_editCell_45', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_editCell_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_insert_Rows', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'spacing', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_insert_Columns', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'padding', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'borders', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'collapse', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'yes', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'no', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'insert', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_insert_btnSpan1', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_insert_btnSpan2', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_insert_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'insert_row', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'insert_column', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_size_IncreaseDecreaseRowspan', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_size_IncreaseDecreaseColspan', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_size_InsertRowAbove', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_size_InsertRowBelow', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_size_InsertColumnLeft', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_size_InsertColumnRight', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_size_IncreaseRowspan', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_size_DecreaseRowspan', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_size_IncreaseColspan', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_size_DecreaseColspan', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'delete_row', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'delete_column', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_size_close', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'cannot_delete_column', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'cannot_delete', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_size_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'character_spacing', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'preview', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'apply_to', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'selected_text', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'current_tag', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'font', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'style', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'size', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'foreground', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'background', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'effects', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'decoration', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'textcase', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'minicaps', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'vertical', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'underline', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'overline', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'linethrough', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'capitalize', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'uppercase', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'lowercase', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'none', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'smallcaps', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'normal', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'not_set', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'superscript', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'subscript', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'relative', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'baseline', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'regular', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'italic', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'bold', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'bold_italic', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'top', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'middle', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'bottom', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'texttop', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'textbottom', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'pick', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'text_formatting', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'url_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_style_selection', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_css_builder', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'editor_lang_remove_formatting', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'paste_text_txtLang', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'ok', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'paste_text_title', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'search_finished', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'spellcheck_btnCheckAgain', 0);
INSERT INTO `tokens` VALUES ('editor_all', 'table_editCell_46', 0);
";

// insert into tokens
foreach (explode(";\n", $queries) as $query) {
    $db->query($query);
}

$queries = "
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Strikethrough', 'Strikethrough', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_FontSize', 'Font Size', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_CustomCSS', 'Custom CSS', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_ParagraphFormatting', 'Paragraph Formatting', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_ListFormatting', 'List Formatting', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_TextFormatting', 'Text Formatting', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_FullScreen', 'Full Screen', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Save', 'Save', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'colors_title', '<title>Colors</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'colors_btnApply', ' Apply ', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'colors_btnRemove', ' Remove color ', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'colors_btnCancel', ' Cancel ', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'colors_btnAddToCustom', 'Add to Custom Colors', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'colors_Current', 'Current', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'colors_New', 'New', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'colors_1', 'Web Pallete', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'characters_title', '<title>Special Characters</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'characters_1', 'HTML Code', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'box_title', '<title>Box Formatting</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'box_Dimension', 'Dimension', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'box_Shading', 'Shading', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'border_title', '<title>Borders</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'bookmark_title', '<title>Bookmark</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_edit_SpanSplitRow', 'Span/Split Row', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Clean', 'Clean', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'colors_NamedColors', 'Named Colors', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Line', 'Line', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_JustifyLeft', 'Justify Left', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_JustifyCenter', 'Justify Center', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_JustifyRight', 'Justify Right', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_JustifyFull', 'Justify Full', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Numbering', 'Numbering', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Bullets', 'Bullets', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Outdent', 'Outdent', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_LeftToRight', 'Left To Right', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_RightToLeft', 'Right To Left', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_ForegroundColor', 'Foreground Color', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_BackgroundColor', 'Background Color', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Hyperlink', 'Hyperlink', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Flash', 'Flash', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Media', 'Media', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_ContentBlock', 'Content Block', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_InternalLink', 'Internal Link', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Object', 'Object', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_InsertTable', 'Insert Table', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_TableSize', 'Table Size', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_EditTable', 'Edit Table', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_EditCell', 'Edit Cell', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Table', 'Table', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Absolute', 'Absolute', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_PastefromWord', 'Paste from Word', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_FormEditor', 'Form Editor', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Form', 'Form', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_TextField', 'Text Field', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_List', 'List', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Checkbox', 'Checkbox', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_RadioButton', 'Radio Button', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_HiddenField', 'Hidden Field', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_FileField', 'File Field', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_ViewEditSource', 'View/Edit Source', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_TagSelector', 'Tag Selector', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_ClearAll', 'Clear All', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Tags', 'Tags', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Heading_1', 'Heading 1', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Heading_2', 'Heading 2', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Heading_3', 'Heading 3', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Heading_4', 'Heading 4', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Heading_5', 'Heading 5', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Heading_6', 'Heading 6', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Preformatted', 'Preformatted', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_NormalP', 'Normal (P)', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_NormalDIV', 'Normal (DIV)', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Size_1', 'Size 1', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Size_2', 'Size 2', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Size_3', 'Size 3', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Size_4', 'Size 4', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Size_5', 'Size 5', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Size_6', 'Size 6', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Size_7', 'Size 7', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_deleteallcontents', 'Are you sure you wish to delete all contents?', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_RemoveTag', 'Remove Tag', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_BoxFormatting', 'Box Formatting', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_AdvancedTableInsert', 'Advanced Table Insert', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_EditTableCell', 'Edit Table/Cell', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Print', 'Print', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_PasteText', 'Paste Text', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'flash_Quality', 'Quality', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'flash_Align', 'Align', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'flash_Loop', 'Loop', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'flash_ClassID', 'Class ID', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'flash_CodeBase', 'CodeBase', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'flash_PluginsPage', 'PluginsPage', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'flash_Low', 'Low', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'flash_NotSet', '<Not Set>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'flash_title', '<title>Insert Flash</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_button_Submit', 'Submit', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_button_title', '<title>Button</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_check_title', '<title>Checkbox</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_file_title', '<title>File Field</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_form_Action', 'Action', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_form_Method', 'Method', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_form_title', '<title>Form</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_hidden_title', '<title>Hidden Field</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_list_Multipleselect', 'Multiple select', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_list_btnAdd', '  add  ', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_list_btnUp', '  up  ', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_list_btnDown', '  down  ', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_list_btnDel', '  del  ', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_list_title', '<title>List</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_radio_title', '<title>Radio Button</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_text_MaxLength', 'Max Length', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_text_NumLine', 'Num Line', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_text_Text', 'Text', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_text_Textarea', 'Textarea', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_text_Password', 'Password', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'form_text_title', '<title>Text Field</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'hyperlink_Page', 'Page', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'hyperlink_Target', 'Target', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'hyperlink_Title', '<title>Hyperlink</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'hyperlink_Linktype', 'Link type', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'hyperlink_Plainlink', 'Plain link', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'hyperlink_Self', 'Self', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'hyperlink_Parent', 'Parent', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'image_Title', '<title>Image</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'image_Border', 'Border', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'image_absBottom', 'absBottom', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'image_absMiddle', 'absMiddle', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'image_textTop_2', 'textTop', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'image_background_Repeat', 'Repeat', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'image_background_VerticalAlign', 'Vertical Align', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'image_background_Norepeat', 'No repeat', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'image_background_Repeathorizontally', 'Repeat horizontally', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'image_background_Repeatvertically', 'Repeat vertically', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'list_Numbered', 'Numbered', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'list_Bulleted', 'Bulleted', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'list_StartingNumber', 'Starting Number', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'list_UsingImageurl', 'Using Image - URL', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'list_Pleaseselectalist', 'Please select a list.', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'list_title', '<title>List Formatting</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'media_AutoStart', 'Auto Start', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'media_ShowControls', 'Show Controls', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'media_ShowStatusBar', 'Show Status Bar', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'media_ShowDisplay', 'Show Display', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'media_AutoRewind', 'Auto Rewind', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'media_title', '<title>Media</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'paragraph_Indentation', 'Indentation', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'paragraph_WordSpacing', 'Word Spacing', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'paragraph_LineHeight', 'Line Height', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'paragraph_TextCase', 'Text Case', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'paragraph_title', '<title>Paragraph Formatting</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'paste_word_title', '<title>Paste From Word</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'percent_title', '<title>Percentage</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'preview_title', '<title>Preview</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'search_Matchcase', 'Match case', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'search_Matchwholeword', 'Match whole word', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'search_btnSearch', 'Search next', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'search_btnReplaceAll', 'Replace all', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'search_title', '<title>Search & Replace</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'source_html_txtLang', 'Wrap Text', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'source_html_title', '<title>Source Editor</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'spellcheck_ieSpell', 'ieSpell (from www.iespell.com) is required.', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'spellcheck_title', '<title>Check Spelling</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'styles_title', '<title>Styles</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_edit_SpanSplitColumn', 'Span/Split Column', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_edit_Fixedtablewidth', 'Fixed table width', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_edit_Fixedtableheight', 'Fixed table height', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_edit_CellSpacing', 'Cell Spacing', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_edit_CellPadding', 'Cell Padding', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_edit_title', '<title>Table Properties</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_editCell_6', 'Fixed cell width', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_editCell_9', 'Fixed cell height', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_editCell_10', 'Text Alignment', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_editCell_btnImage', ' Image', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_editCell_btnText', ' Text Formatting ', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_editCell_30', 'sub', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_editCell_31', 'super', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_editCell_43', 'Current Cell', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_editCell_44', 'Current Row', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_editCell_45', 'Current Column', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_editCell_title', '<title>Cell Properties</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_insert_Rows', 'Rows', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_insert_Columns', 'Columns', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_insert_btnSpan1', 'Span v', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_insert_btnSpan2', 'Span >', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_insert_title', '<title>Insert Table</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_size_IncreaseDecreaseRowspan', 'Increase/Decrease<br>Rowspan', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_size_IncreaseDecreaseColspan', 'Increase/Decrease<br>Colspan', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_size_InsertRowAbove', 'Insert Row (Above)', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_size_InsertRowBelow', 'Insert Row (Below)', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_size_InsertColumnRight', 'Insert Column (Right)', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_size_IncreaseRowspan', 'Increase Rowspan', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_size_DecreaseRowspan', 'Decrease Rowspan', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_size_IncreaseColspan', 'Increase Colspan', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_size_DecreaseColspan', 'Decrease Colspan', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_size_close', ' Close ', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_size_title', '<title>Table Size</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'url_title', '<title>URL</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_style_selection', 'Style Selection', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_css_builder', 'CSS Builder', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_remove_formatting', 'Remove Formatting', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'paste_text_title', '<title>Paste Text</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'spellcheck_btnCheckAgain', ' Check Again ', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_editCell_46', 'Whole Table', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'search_finished', 'Finished searching the document. Search again from the top?', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'colors_216WebSafe', '216 Web Safe', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_CheckSpelling', 'Check Spelling', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_FontName', 'Font Name', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Indent', 'Indent', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_Paragraph', 'Paragraph', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_ShowHideGuidelines', 'Show/Hide Guidelines', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_SpecialCharacters', 'Special Characters', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'flash_High', 'High', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'hyperlink_Blank', 'Blank', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'hyperlink_Imagelink', 'Image link, open in new window', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'paste_text_txtLang', 'Paste text content here (CTRL+V) ', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'paste_word_txtLang', 'Paste Word content here (CTRL+V) ', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'alignment', 'Alignment', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'apply', 'Apply', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'apply_to', 'Apply to', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'background', 'Background', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'background_image', '<title>Background Image</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'bold', 'Bold', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'bold_italic', 'Bold Italic', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'bookmark', 'Bookmark', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'borders', 'Borders', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'border_style', ' Border Style ', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'bottom', 'Bottom', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'button', 'Button', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'cancel', 'Cancel', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'cannot_delete', 'Cannot delete row. The row contains spanned cells from another rows. Please remove the span first.', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'center', 'center', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'color', 'Color', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'close', 'close', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'checked', 'Checked', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'character_spacing', 'Character Spacing', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'copy', 'Copy', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'css_text', 'CSS Text', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'custom_colors', 'Custom Colors', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'custom_css', '<title>Custom CSS</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'cut', 'Cut', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'decoration', 'Decoration', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'default', 'Default', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'delete_row', 'Delete Row', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'delete_column', 'Delete Column', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'effects', 'Effects', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'font', 'Font', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'height', 'Height', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'image', 'Image', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'image_background_HorizontalAlign', 'Horizontal Align', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'insert', 'Insert', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'insert_column', 'Insert Column', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'insert_row', 'Insert Row', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'italic', 'Italic', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'left', 'Left', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'left_border', 'Left Border', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'more_colors', 'More Colors...', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'no', 'No', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'none', 'None', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'normal', 'Normal', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'no_border', 'No Border', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'ok', ' Ok ', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'outside_border', 'Outside Border', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'paste', 'Paste', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'percent', 'percent', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'pixels', 'pixels', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'please_select_a_text', 'Please select a text.', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'preview', 'Preview', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'properties', 'Properties', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'redo', 'Redo', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'replace', 'Replace', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'right_border', 'Right Border', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'right', 'Right', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'selected_text', 'Selected Text', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'size', 'Size', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'spacing', 'Spacing', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'style', 'Style', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'styles', 'Styles', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'subscript', 'Subscript', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'superscript', 'Superscript', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'table_size_InsertColumnLeft', 'Insert Column (Left)', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'text_formatting', '<title>Text Formatting</title>', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'undo', 'Undo', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'yes', 'Yes', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'youre_selecting_body_element', 'You''re selecting BODY element.', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'width', 'Width', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'vertical', 'Vertical', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'white_space', 'White Space', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'value', 'Value', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'uppercase', 'Uppercase', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'underline', 'Underline', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'unchecked', 'Unchecked', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'type', 'Type', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'top_border', 'Top Border', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'top', 'Top', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'texttop', 'text-top', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'textcase', 'TextCase', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'textbottom', 'text-bottom', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'source', 'Source', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'smallcaps', 'Small-Caps', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'search', 'Search', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'reset', 'Reset', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'relative', 'Relative', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'regular', 'Regular', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'pre', 'pre', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'pick', 'Pick', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'padding', 'Padding', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'overline', 'Overline', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'no_wrap', 'No Wrap', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'not_set', 'Not Set', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'minicaps', 'Minicaps', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'middle', 'middle', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'margin', 'Margin', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'lowercase', 'Lowercase', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'linethrough', 'Line-through', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'left_margin', 'Left Margin', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'image_background_ImageSource', 'Image Source', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'current_tag', 'Current Tag', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'collapse', 'Collapse', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'class_name', 'Class Name', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'capitalize', 'Capitalize', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'cannot_delete_column', 'Cannot delete column. The column contains spanned cells from another column. Please remove the span first.', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'bottom_border', 'Bottom Border', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'baseline', 'baseline', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'autofit_to_window', 'AutoFit to window', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'autofit_to_contents', 'AutoFit to contents', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'autofit', 'AutoFit', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_BorderShading', 'Border & Shading', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'editor_lang_StylesFormatting', 'Styles & Formatting', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'foreground', 'Foreground', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'justify', 'Justify', -1, 'en');
INSERT INTO `translations` VALUES ('editor_all', 'name', 'Name', -1, 'en');
";

// insert into translations
foreach (explode(";\n", $queries) as $query) {
    $db->query($query);
}

echo "<li>translations for category <em>`editor_all`</em> updated</li>\n";

?>
</ul>
</body>
</html>